### ISSUE TITLE
Error executing the AMD64 .msi on Win10

### ISSUE THREAD

**Issue by ghost** [pierreprinetti/itaqrawl#1]
Microsoft Windows [Versione 10.0.14393]
Upon executing the amd64 version I receive the following error:
![errore_tastiera](https://cloud.githubusercontent.com/assets/23333079/20267793/a74d58ee-aa7c-11e6-8a34-72f0e0b64b2a.png)

Looks like you did not upload all the files.

**Comment by pierreprinetti** [comment]
Did you manage to make it work? I couldn't reproduce the issue.
